---
# XAI Server Setup - Security hardening and base configuration
#
# Prepares servers with security hardening, packages, and system tuning.
# Run this before main.yml on fresh servers.
#
# Usage:
#   ansible-playbook -i inventory/testnet.yml setup.yml
#   ansible-playbook -i inventory/testnet.yml setup.yml --limit xai_node1

- name: XAI Server Preparation
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # =========================================================================
    # APT and Base Packages
    # =========================================================================
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base packages
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present

    - name: Set timezone to UTC
      community.general.timezone:
        name: "{{ timezone | default('UTC') }}"

    # =========================================================================
    # SSH Hardening
    # =========================================================================
    - name: Configure SSH hardening
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin {{ ssh_permit_root | default("no") }}' }
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication {{ ssh_password_auth | default("no") }}' }
        - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
        - { regexp: '^#?PermitEmptyPasswords', line: 'PermitEmptyPasswords no' }
        - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }
        - { regexp: '^#?MaxAuthTries', line: 'MaxAuthTries 3' }
        - { regexp: '^#?ClientAliveInterval', line: 'ClientAliveInterval 300' }
        - { regexp: '^#?ClientAliveCountMax', line: 'ClientAliveCountMax 2' }
      notify: Restart sshd

    # =========================================================================
    # Firewall (UFW)
    # =========================================================================
    - name: Configure UFW defaults
      community.general.ufw:
        direction: "{{ item.direction }}"
        policy: "{{ item.policy }}"
      loop:
        - { direction: incoming, policy: "{{ ufw_default_incoming | default('deny') }}" }
        - { direction: outgoing, policy: "{{ ufw_default_outgoing | default('allow') }}" }
      when: ufw_enabled | default(true)

    - name: Allow SSH through UFW
      community.general.ufw:
        rule: allow
        port: "{{ ssh_port | default(22) }}"
        proto: tcp
      when: ufw_enabled | default(true)

    - name: Enable UFW
      community.general.ufw:
        state: enabled
      when: ufw_enabled | default(true)

    # =========================================================================
    # Fail2ban
    # =========================================================================
    - name: Configure fail2ban for SSH
      ansible.builtin.copy:
        content: |
          [sshd]
          enabled = true
          port = {{ ssh_port | default(22) }}
          filter = sshd
          logpath = /var/log/auth.log
          maxretry = 3
          bantime = 3600
          findtime = 600
        dest: /etc/fail2ban/jail.local
        mode: '0644'
      notify: Restart fail2ban

    - name: Enable fail2ban service
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true

    # =========================================================================
    # System Tuning for Blockchain
    # =========================================================================
    - name: Configure sysctl for blockchain performance
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: true
        state: present
        reload: true
      loop:
        - { key: 'net.core.somaxconn', value: '65535' }
        - { key: 'net.ipv4.tcp_max_syn_backlog', value: '65535' }
        - { key: 'net.core.netdev_max_backlog', value: '65535' }
        - { key: 'net.ipv4.tcp_tw_reuse', value: '1' }
        - { key: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
        - { key: 'vm.swappiness', value: '10' }
        - { key: 'fs.file-max', value: '2097152' }
        - { key: 'fs.inotify.max_user_watches', value: '524288' }

    - name: Configure ulimits for blockchain
      ansible.builtin.copy:
        content: |
          # XAI blockchain ulimits
          *               soft    nofile          65535
          *               hard    nofile          65535
          *               soft    nproc           65535
          *               hard    nproc           65535
          {{ daemon_user | default('ubuntu') }}    soft    nofile          65535
          {{ daemon_user | default('ubuntu') }}    hard    nofile          65535
        dest: /etc/security/limits.d/99-xai.conf
        mode: '0644'

    # =========================================================================
    # Journald Limits
    # =========================================================================
    - name: Create journald config directory
      ansible.builtin.file:
        path: /etc/systemd/journald.conf.d
        state: directory
        mode: '0755'

    - name: Configure journald limits
      ansible.builtin.copy:
        content: |
          [Journal]
          SystemMaxUse=2G
          SystemKeepFree=4G
          SystemMaxFileSize=200M
          MaxRetentionSec=1week
        dest: /etc/systemd/journald.conf.d/limits.conf
        mode: '0644'
      notify: Restart journald

    # =========================================================================
    # Unattended Upgrades
    # =========================================================================
    - name: Install unattended-upgrades
      ansible.builtin.apt:
        name:
          - unattended-upgrades
          - apt-listchanges
        state: present

    - name: Configure unattended-upgrades
      ansible.builtin.copy:
        content: |
          Unattended-Upgrade::Allowed-Origins {
            "${distro_id}:${distro_codename}";
            "${distro_id}:${distro_codename}-security";
            "${distro_id}ESMApps:${distro_codename}-apps-security";
            "${distro_id}ESM:${distro_codename}-infra-security";
          };
          Unattended-Upgrade::Package-Blacklist {
          };
          Unattended-Upgrade::DevRelease "auto";
          Unattended-Upgrade::AutoFixInterruptedDpkg "true";
          Unattended-Upgrade::MinimalSteps "true";
          Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
          Unattended-Upgrade::Remove-Unused-Dependencies "true";
          // DISABLED for blockchain - manual reboot required
          Unattended-Upgrade::Automatic-Reboot "false";
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: '0644'

    - name: Enable automatic updates
      ansible.builtin.copy:
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
          APT::Periodic::AutocleanInterval "7";
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: '0644'

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Restart fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: restarted

    - name: Restart journald
      ansible.builtin.service:
        name: systemd-journald
        state: restarted
