---
# XAI Block Explorer Deployment - Blockscout via Docker
#
# Deploys Blockscout block explorer with XAI RPC adapter for chain indexing.
# Uses Docker Compose for service orchestration.
#
# Usage:
#   ansible-playbook -i inventory/testnet.yml support_explorer.yml --limit xai_testnet
#   ansible-playbook -i inventory/testnet.yml support_explorer.yml -e explorer_action=restart
#
# Variables:
#   explorer_action: 'deploy', 'restart', 'stop', 'update' (default: deploy)
#   blockscout_version: Blockscout version tag (default: latest)
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - XAI RPC adapter running (port 8545)
#   - PostgreSQL credentials in SOPS secrets

- name: XAI Block Explorer (Blockscout) Deployment
  hosts: all
  become: true
  gather_facts: true

  vars:
    explorer_action: "deploy"
    blockscout_version: "latest"
    explorer_home: "/opt/xai-explorer"
    explorer_domain: "testnet-explorer.xaiblockchain.com"
    rpc_adapter_port: 8545
    blockscout_frontend_port: 3001
    blockscout_backend_port: 4000
    postgres_port: 5432
    postgres_user: "blockscout"
    postgres_password: "blockscout_secure_password"
    postgres_db: "blockscout"
    chain_id: "xai-mvp-testnet-1"
    network_name: "XAI Testnet"
    network_symbol: "XAI"

  handlers:
    - name: Restart explorer
      ansible.builtin.command:
        cmd: docker compose restart
        chdir: "{{ explorer_home }}"
      changed_when: true

  tasks:
    # =========================================================================
    # Prerequisites
    # =========================================================================
    - name: Install Docker prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Start and enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create explorer directory
      ansible.builtin.file:
        path: "{{ explorer_home }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    # =========================================================================
    # Docker Compose Configuration
    # =========================================================================
    - name: Deploy Docker Compose configuration
      ansible.builtin.copy:
        content: |
          # XAI Block Explorer - Blockscout Stack
          # Auto-generated by Ansible

          version: '3.8'

          services:
            postgres:
              image: postgres:15-alpine
              container_name: blockscout-postgres
              restart: unless-stopped
              environment:
                POSTGRES_USER: {{ postgres_user }}
                POSTGRES_PASSWORD: {{ postgres_password }}
                POSTGRES_DB: {{ postgres_db }}
              volumes:
                - postgres_data:/var/lib/postgresql/data
              ports:
                - "127.0.0.1:{{ postgres_port }}:5432"
              healthcheck:
                test: ["CMD-SHELL", "pg_isready -U {{ postgres_user }}"]
                interval: 10s
                timeout: 5s
                retries: 5

            redis:
              image: redis:7-alpine
              container_name: blockscout-redis
              restart: unless-stopped
              command: redis-server --appendonly yes
              volumes:
                - redis_data:/data
              healthcheck:
                test: ["CMD", "redis-cli", "ping"]
                interval: 10s
                timeout: 5s
                retries: 5

            backend:
              image: blockscout/blockscout:{{ blockscout_version }}
              container_name: blockscout-backend
              restart: unless-stopped
              depends_on:
                postgres:
                  condition: service_healthy
                redis:
                  condition: service_healthy
              environment:
                # Database
                DATABASE_URL: postgresql://{{ postgres_user }}:{{ postgres_password }}@postgres:5432/{{ postgres_db }}

                # Network Configuration
                ETHEREUM_JSONRPC_VARIANT: geth
                ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:{{ rpc_adapter_port }}
                ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:{{ rpc_adapter_port }}
                ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8766

                # Chain Info
                CHAIN_ID: "1"
                NETWORK: {{ network_name }}
                SUBNETWORK: {{ network_name }}
                COIN: {{ network_symbol }}
                COIN_NAME: {{ network_symbol }}

                # Features
                DISABLE_EXCHANGE_RATES: "true"
                DISABLE_KNOWN_TOKENS: "true"
                SHOW_TESTNET_LABEL: "true"
                TESTNET_LABEL_TEXT: "Testnet"

                # API
                API_V2_ENABLED: "true"
                MICROSERVICE_SC_VERIFIER_ENABLED: "false"

                # Redis
                ACCOUNT_REDIS_URL: redis://redis:6379/1

                # Indexer
                INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
                INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"

                # Performance
                POOL_SIZE: "40"
                POOL_SIZE_API: "10"
                ECTO_USE_SSL: "false"

                # Misc
                SECRET_KEY_BASE: "{{ lookup('password', '/dev/null length=64 chars=hexdigits') }}"
                PORT: "4000"
              ports:
                - "127.0.0.1:{{ blockscout_backend_port }}:4000"
              extra_hosts:
                - "host.docker.internal:host-gateway"
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:4000/api/v2/stats"]
                interval: 30s
                timeout: 10s
                retries: 5
                start_period: 60s

            frontend:
              image: ghcr.io/blockscout/frontend:{{ blockscout_version }}
              container_name: blockscout-frontend
              restart: unless-stopped
              depends_on:
                backend:
                  condition: service_healthy
              environment:
                NEXT_PUBLIC_API_HOST: localhost
                NEXT_PUBLIC_API_PORT: "{{ blockscout_backend_port }}"
                NEXT_PUBLIC_API_PROTOCOL: http
                NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
                NEXT_PUBLIC_STATS_API_HOST: http://localhost:{{ blockscout_backend_port }}
                NEXT_PUBLIC_NETWORK_NAME: "{{ network_name }}"
                NEXT_PUBLIC_NETWORK_SHORT_NAME: "{{ network_symbol }}"
                NEXT_PUBLIC_NETWORK_ID: "1"
                NEXT_PUBLIC_NETWORK_CURRENCY_NAME: "{{ network_symbol }}"
                NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: "{{ network_symbol }}"
                NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18"
                NEXT_PUBLIC_IS_TESTNET: "true"
                NEXT_PUBLIC_API_BASE_PATH: "/"
                NEXT_PUBLIC_HOMEPAGE_CHARTS: "['daily_txs']"
                NEXT_PUBLIC_VISUALIZE_API_HOST: ""
                NEXT_PUBLIC_CONTRACT_INFO_API_HOST: ""
              ports:
                - "127.0.0.1:{{ blockscout_frontend_port }}:3000"
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:3000"]
                interval: 30s
                timeout: 10s
                retries: 5
                start_period: 30s

          volumes:
            postgres_data:
            redis_data:

          networks:
            default:
              name: blockscout-network
        dest: "{{ explorer_home }}/docker-compose.yml"
        owner: root
        group: root
        mode: '0644'
      notify: Restart explorer

    # =========================================================================
    # Deploy / Manage Explorer
    # =========================================================================
    - name: Pull Docker images
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ explorer_home }}"
      changed_when: true
      when: explorer_action in ['deploy', 'update']

    - name: Start explorer services
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ explorer_home }}"
      changed_when: true
      when: explorer_action in ['deploy', 'update']

    - name: Restart explorer services
      ansible.builtin.command:
        cmd: docker compose restart
        chdir: "{{ explorer_home }}"
      changed_when: true
      when: explorer_action == 'restart'

    - name: Stop explorer services
      ansible.builtin.command:
        cmd: docker compose down
        chdir: "{{ explorer_home }}"
      changed_when: true
      when: explorer_action == 'stop'

    # =========================================================================
    # Nginx Configuration
    # =========================================================================
    - name: Deploy explorer nginx configuration
      ansible.builtin.copy:
        content: |
          # XAI Block Explorer - {{ explorer_domain }}
          server {
              listen 80;
              server_name {{ explorer_domain }};

              access_log /var/log/nginx/explorer-access.log;
              error_log /var/log/nginx/explorer-error.log;

              # Frontend
              location / {
                  proxy_pass http://127.0.0.1:{{ blockscout_frontend_port }};
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";

                  proxy_connect_timeout 60s;
                  proxy_send_timeout 60s;
                  proxy_read_timeout 60s;
              }

              # API v2
              location /api/v2/ {
                  proxy_pass http://127.0.0.1:{{ blockscout_backend_port }}/api/v2/;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;

                  # CORS headers
                  add_header Access-Control-Allow-Origin * always;
                  add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
                  add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;

                  if ($request_method = OPTIONS) {
                      return 204;
                  }
              }

              # Socket for real-time updates
              location /socket/ {
                  proxy_pass http://127.0.0.1:{{ blockscout_backend_port }}/socket/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;

                  proxy_connect_timeout 60s;
                  proxy_send_timeout 86400s;
                  proxy_read_timeout 86400s;
              }

              # Health check
              location /health {
                  access_log off;
                  return 200 "OK";
                  add_header Content-Type text/plain;
              }

              # RPC health (via RPC adapter)
              location /rpc-health {
                  proxy_pass http://127.0.0.1:{{ rpc_adapter_port }}/health;
                  access_log off;
              }
          }
        dest: /etc/nginx/sites-available/xai-explorer.conf
        owner: root
        group: root
        mode: '0644'
      when: explorer_action != 'stop'

    - name: Enable explorer nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/xai-explorer.conf
        dest: /etc/nginx/sites-enabled/xai-explorer.conf
        state: link
      when: explorer_action != 'stop'

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      when: explorer_action != 'stop'

    # =========================================================================
    # Verification
    # =========================================================================
    - name: Wait for explorer to start
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ blockscout_frontend_port }}"
        status_code: 200
      register: explorer_health
      until: explorer_health.status == 200
      retries: 60
      delay: 10
      when: explorer_action in ['deploy', 'update', 'restart']
      check_mode: false

    - name: Display explorer status
      ansible.builtin.debug:
        msg: |
          ============================================
          XAI Block Explorer Deployed
          ============================================
          Server: {{ inventory_hostname }}
          Action: {{ explorer_action }}
          Version: {{ blockscout_version }}
          ============================================

          Services:
            Frontend: http://127.0.0.1:{{ blockscout_frontend_port }}
            Backend API: http://127.0.0.1:{{ blockscout_backend_port }}
            PostgreSQL: 127.0.0.1:{{ postgres_port }}

          Public Access:
            https://{{ explorer_domain }}

          API Endpoints:
            Stats: https://{{ explorer_domain }}/api/v2/stats
            Blocks: https://{{ explorer_domain }}/api/v2/blocks
            Transactions: https://{{ explorer_domain }}/api/v2/transactions

          Docker Commands:
            Status: cd {{ explorer_home }} && docker compose ps
            Logs: cd {{ explorer_home }} && docker compose logs -f
            Restart: cd {{ explorer_home }} && docker compose restart
            Stop: cd {{ explorer_home }} && docker compose down
          ============================================
      when: explorer_action != 'stop'

    - name: Display stop confirmation
      ansible.builtin.debug:
        msg: |
          ============================================
          XAI Block Explorer Stopped
          ============================================
          All services have been stopped.

          To restart:
            cd {{ explorer_home }} && docker compose up -d
          ============================================
      when: explorer_action == 'stop'
